# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 21:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知', max_length=45)),
                ('description', models.CharField(default='', max_length=205)),
                ('pic', models.CharField(default='default_book_pic.gif', max_length=80)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('newreply', models.IntegerField(default=0)),
                ('last_reply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WildBookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知', max_length=45)),
                ('description', models.CharField(default='', max_length=200)),
                ('owner', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WildBookReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, verbose_name='回复内容')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加的时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudlibrary.WildBook', verbose_name='所属书籍')),
            ],
        ),
        migrations.CreateModel(
            name='WildUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qq', models.CharField(default='', max_length=13)),
                ('tel', models.CharField(default='', max_length=15)),
                ('weixin', models.CharField(default='', max_length=30)),
                ('nickname', models.CharField(default='', max_length=30)),
                ('headpic', models.CharField(default='icon_default_head.jpg', max_length=50)),
                ('newreply', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='wildbookreply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudlibrary.WildUser', verbose_name='发表留言的用户'),
        ),
        migrations.AddField(
            model_name='wildbook',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudlibrary.WildUser'),
        ),
    ]
