# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='未分类', max_length=20)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudlibrary.BookTag')),
            ],
        ),
        migrations.AddField(
            model_name='wildbook',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='cloudlibrary.BookTag'),
        ),
    ]
