# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlibrary', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildbook',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cloudlibrary.BookTag'),
        ),
    ]
