# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlibrary', '0010_wildbookadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildbookadd',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
