# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlibrary', '0011_auto_20160426_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildBookHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('owner', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WildBookAdd',
        ),
    ]
